layout_spectrum: 0.3960573
color:
  saturation: 0.1909701
  brandStrength: 0.6379929
  lightness: 0.7150537
  brandColors:
    - '#FF01FF'
    - '#2D0333'
    - '#FFFFFF'
    - '#6D2565'
    - '#FBA7FB'
  rhythmicContrast: 0.4138694
typography_spectrum: 0.5143369
name: LEDs and Cactus
