layout_spectrum: 0.3960573
color:
  saturation: 0.1909701
  brandStrength: 0.9534175
  lightness: 0.7150537
  rhythmicContrast: 0.4138694
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.5143369
name: LEDs and Cactus
